sudo: required
services:
  - docker
dist: trusty
language: python
python:
  - "2.7"
script: _tests/docker_build
deploy:
  provider: firebase
  token:
  secure: "aA6in0AWi8YvZZyx8g0hM8V3V4bjxoJgCYzMIzI9wiY1wbQj4RXEiYgnmxRsxzranoJbboBRj6+v/Adt/aeHcSclS9Cog2fRlG0FtTOZOHIVxz1ZXx1QmXwfWQbUyFZnpsUvKD3DuM4O8oYOxkmrqAKEF5mLw3YcEVKnXN8n3xnrEViQlrMOFP/PljcgiPgMKeZHD8n/EW0SdQeM0c4QTqUqvebrjALykkKkghdW2htuDrtiiE4vWwDzYxoUyoSZLS8hK3cwmFCFdMl5i9rkLOknJ6TTM037RD+Y4OCIf4gvRqWqh03KXFmvzU39I5ry45t5gETkkktmjmLhfymC8ITWrjDrZmeD5Iz/7ArMkKfVEkPANVObJd7VM3sWUpMbDv7rKpgW2rbQvgn7IPG9SK1i28NQCF7gqLaU/F1RVhFMl8K3LCOgEHX2YO16cMts5J4n9Mt4X4EO5vmAKqBinRo1SQwd8mgWU4OPSbc0Vp46ZZdcjrJlGa3T3TCeE4GjtwjM1llC19sMgP/umw2Fi1Uest6oaAnKZZtPzXrpcUKuRQy9vzwIZ/Wg5pwXesIorY9grCiKTLO0X258TWPLp8VCGMmvrBuSgLSTYg8/LRL8L4M+HqyOOUhdqruxJpHIjGTNUSwXLqCWu7zOKeb4E704LGp/mSuTnAx62vHHdSY="
  skip_cleanup: true
notifications:
  email:
    on_failure: change
